[project]
authors = ["Ryan Oates <ryanoatie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mistral_client"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies] 
max = ">=25.4.0.dev2025060220,<26"
openai = ">=1.84.0,<2"
anthropic = ">=0.52.2,<0.53"
pip = ">=25.1.1,<26"
flake8 = ">=7.2.0,<8"
black = ">=25.1.0,<26"
python-dotenv = ">=1.1.0,<2"
requests = ">=2.32.3,<3"
pytest = ">=8.4.0,<9"
mypy = ">=1.16.0,<2"
isort = ">=6.0.1,<7"
pylint = ">=3.3.7,<4"
pre-commit = ">=4.2.0,<5"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
transformers = ">=4.52.4,<5"
tqdm = ">=4.67.1,<5"
rich = ">=14.0.0,<15"
typer = ">=0.16.0,<0.17"
fastapi = ">=0.115.4,<0.116"
uvicorn = ">=0.34.3,<0.35"
httpx = ">=0.28.1,<0.29"
gradle = ">=8.11.1,<9"
flask = ">=3.1.1,<4"
mistralai = ">=0.4.2,<0.5"
fire = ">=0.7.0,<0.8"


