[project]
authors = ["Ryan Oates <ryanoatie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mistral_client"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies] 
max = ">=25.3.0.dev2025032805,<26"
openai = ">=1.68.2,<2"
anthropic = ">=0.49.0,<0.50"
pip = ">=25.0.1,<26"
flake8 = ">=7.1.2,<8"
black = ">=25.1.0,<26"
python-dotenv = ">=1.1.0,<2"
requests = ">=2.32.3,<3"
pytest = ">=8.3.5,<9"
mypy = ">=1.15.0,<2"
isort = ">=6.0.1,<7"
pylint = ">=3.3.5,<4"
pre-commit = ">=4.2.0,<5"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
matplotlib = ">=3.10.1,<4"
seaborn = ">=0.13.2,<0.14"
transformers = ">=4.50.0,<5"
tqdm = ">=4.67.1,<5"
rich = ">=13.9.4,<14"
typer = ">=0.15.2,<0.16"
fastapi = ">=0.115.4,<0.116"
uvicorn = ">=0.34.0,<0.35"
httpx = ">=0.28.1,<0.29"
gradle = ">=8.11.1,<9"


