/*
 * This source file was generated by the Gradle 'init' task
 */
package mistral_client;

import java.util.logging.Level;
import java.util.logging.Logger;

public class App {
    private static final Logger LOG = Logger.getLogger(App.class.getName());
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LOG.info(new App().getGreeting());
    }
}
